#Windows Server 2019 Desktop
schedules:
  - cron: "30 12 26 * *"
    always: true
    displayName: Monthly Schedule
    branches:
      include:
        - main
resources:
  repositories:
    - repository: repo-name
      type: github
      endpoint: Github-org-or-user
      name: smctighevcp/repo-name
      ref: main

pr: none
trigger: none
jobs:
  - job: Windows_Server_2019_Desktop
    pool:
    name: On-Prem Agent Pool
    timeoutInMinutes: 120
    variables:
      - group: Notifications
    steps:
      - task: AzureKeyVault@2
        displayName: Aquiring Secrets
        inputs:
          azureSubscription: "identity-management-connectivity(*******************************)"
          KeyVaultName: "kv-vault-main"
          SecretsFilter: "DevOpsGitHubPAT, vSphereAdmin, vSphereAdminUser, GuestLocalAdmin, GuestLocalAdminUser, PipelineNotificationsTenantID, PipelineNotificationsAppID, PipelineNotificationsAppSecret"
          RunAsPreJob: false
      - task: PowerShell@2
        displayName: Creating Environment Variables and Initiating Build
        inputs:
          targetType: "inline"
          script: |
            $env:PKR_VAR_env_vsphere_username = "$(vSphereAdminUser)"
            $env:PKR_VAR_env_vsphere_password = "$(vSphereAdmin)"
            $env:PKR_VAR_env_communicator_username = "$(GuestLocalAdminUser)"
            $env:PKR_VAR_env_communicator_password = "$(GuestLocalAdmin)"

              #change to Packer working directory
            Set-Location $(System.DefaultWorkingDirectory)\<repo-name>\Packer\pipeline-templates\

              #Specify the Build
              $BuildVersion = "$(BuildVersion)"
              $BuildDate = get-date -f yyyyMMdd-HHmm

              #Enable and set logging location
              $env:PACKER_LOG = 1
              $env:PACKER_LOG_PATH = "C:\Packer-Logs\packerlog-$($BuildVersion)-$BuildDate.txt"

              #Initialise template!
              packer init build.pkr.hcl

              #Build template!
              packer build --only vsphere-iso.win-2019-std-dexp -var-file="vars/windows-server-2019.pkrvars.hcl" .

            #Build Email Content
            $EmailContent = Get-Content $env:PACKER_LOG_PATH
            $EmailBody = '<HTML><H1><font color = "#286334"> Notification from Packer Build Pipeline</font></H1><BODY><font color =#99000 face=Microsoft Tai le><p>Please Review the logfile below for the build and take appropirate action if required.</p><p>$(BuildVersion)</p></font><p>$($EmailContent)</p><p><img src="https://stephanmctighe.files.wordpress.com/2022/03/thesmallhumancloud-logo.png" width="100" height="36"></p>'
            Set-Location $(System.DefaultWorkingDirectory)
            . '.\<repo-name>\functions\Send-Email.ps1'
            Send-Email -TenantId "$(PipelineNotificationsTenantID)" -AppId "$(PipelineNotificationsAppID)" -AppSecret "$(PipelineNotificationsAppSecret)" -From "$(From)" -Recipient "$(Recipient)" -Subject "$(Subject)" -EmailBody $EmailBody
